"use client";

import { useState, useEffect, useCallback, useRef } from "react";
import type {
  AMWorkspaceDetailResponse,
  TalkingPointsData,
  TalkingPointsUpdateResponse,
} from "@/lib/types/am-summary";

interface UseAMWorkspaceDetailReturn {
  data: AMWorkspaceDetailResponse | null;
  isLoading: boolean;
  error: string | null;
  refetch: () => void;
  // Talking Points
  talkingPoints: TalkingPointsData | null;
  savingNotes: boolean;
  saveStatus: "idle" | "saving" | "saved" | "error";
  updateUserNotes: (notes: string) => void;
  loadWeek: (weekStart: string) => void;
  selectedWeek: string;
}

export function useAMWorkspaceDetail(workspace: string): UseAMWorkspaceDetailReturn {
  const [data, setData] = useState<AMWorkspaceDetailResponse | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const [talkingPoints, setTalkingPoints] = useState<TalkingPointsData | null>(null);
  const [savingNotes, setSavingNotes] = useState(false);
  const [saveStatus, setSaveStatus] = useState<"idle" | "saving" | "saved" | "error">("idle");
  const [selectedWeek, setSelectedWeek] = useState("");

  const debounceTimer = useRef<ReturnType<typeof setTimeout> | null>(null);

  const fetchDetail = useCallback(async () => {
    setIsLoading(true);
    setError(null);

    try {
      const url = `/api/am-summary/${encodeURIComponent(workspace)}`;
      const response = await fetch(url);

      if (!response.ok) {
        const body = await response.json().catch(() => ({}));
        throw new Error(body.error ?? `Request failed with status ${response.status}`);
      }

      const json: AMWorkspaceDetailResponse = await response.json();
      setData(json);
      setTalkingPoints(json.talkingPoints);
      if (json.talkingPoints.weekStart) {
        setSelectedWeek(json.talkingPoints.weekStart);
      }
    } catch (err) {
      const message = err instanceof Error ? err.message : "Failed to load workspace details";
      setError(message);
    } finally {
      setIsLoading(false);
    }
  }, [workspace]);

  useEffect(() => {
    fetchDetail();
  }, [fetchDetail]);

  // Cleanup debounce timer on unmount
  useEffect(() => {
    return () => {
      if (debounceTimer.current) {
        clearTimeout(debounceTimer.current);
      }
    };
  }, []);

  const saveNotes = useCallback(
    async (notes: string, weekStart: string) => {
      setSavingNotes(true);
      setSaveStatus("saving");

      try {
        const response = await fetch("/api/am-summary/talking-points", {
          method: "PUT",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            workspace,
            weekStart,
            userNotes: notes,
          }),
        });

        if (!response.ok) {
          throw new Error("Failed to save talking points");
        }

        const result: TalkingPointsUpdateResponse = await response.json();
        setSaveStatus("saved");
        setTalkingPoints((prev) =>
          prev ? { ...prev, userNotes: notes, updatedAt: result.updatedAt } : prev
        );

        // Reset saved indicator after 3 seconds
        setTimeout(() => setSaveStatus("idle"), 3000);
      } catch {
        setSaveStatus("error");
        setTimeout(() => setSaveStatus("idle"), 3000);
      } finally {
        setSavingNotes(false);
      }
    },
    [workspace]
  );

  const updateUserNotes = useCallback(
    (notes: string) => {
      // Update local state immediately
      setTalkingPoints((prev) => (prev ? { ...prev, userNotes: notes } : prev));

      // Debounce the save
      if (debounceTimer.current) {
        clearTimeout(debounceTimer.current);
      }

      debounceTimer.current = setTimeout(() => {
        saveNotes(notes, selectedWeek);
      }, 3000);
    },
    [saveNotes, selectedWeek]
  );

  const loadWeek = useCallback(
    async (weekStart: string) => {
      setSelectedWeek(weekStart);

      try {
        const params = new URLSearchParams({
          workspace,
          week: weekStart,
        });
        const response = await fetch(`/api/am-summary/talking-points?${params.toString()}`);

        if (!response.ok) {
          throw new Error("Failed to load talking points");
        }

        const json = await response.json();
        setTalkingPoints({
          autoGenerated: json.auto_generated ?? "",
          userNotes: json.user_notes ?? "",
          weekStart: json.week_start ?? weekStart,
          updatedAt: json.updated_at ?? null,
        });
      } catch {
        // On error, keep current state
      }
    },
    [workspace]
  );

  return {
    data,
    isLoading,
    error,
    refetch: fetchDetail,
    talkingPoints,
    savingNotes,
    saveStatus,
    updateUserNotes,
    loadWeek,
    selectedWeek,
  };
}
