"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Copy, Check, X } from "lucide-react";
import { toast } from "sonner";
import type {
  AMWorkspaceDetailResponse,
  AMNotableConversation,
  EmergingRisk,
} from "@/lib/types/am-summary";

interface AMCopyButtonProps {
  data: AMWorkspaceDetailResponse;
  userNotes: string;
}

function buildHealthEmoji(status: string): string {
  switch (status) {
    case "green":
      return "Healthy";
    case "yellow":
      return "Needs Attention";
    case "red":
      return "Critical";
    default:
      return status;
  }
}

function buildTrendLabel(trend: string | null): string {
  switch (trend) {
    case "up":
      return "up";
    case "down":
      return "down";
    case "stable":
      return "stable";
    default:
      return "--";
  }
}

function buildMarkdown(data: AMWorkspaceDetailResponse, userNotes: string): string {
  const lines: string[] = [];

  // Header
  lines.push(`## ${data.workspace} — Woche ${data.dateRange.start} - ${data.dateRange.end}`);
  lines.push("");

  // Health & KPIs
  lines.push(`**Health:** ${buildHealthEmoji(data.healthStatus)}`);
  lines.push(
    `**Connections (7d):** ${data.kpis.connectionsSent.current} (${buildTrendLabel(data.kpis.connectionsSent.trend)})`
  );
  lines.push(
    `**Acceptance Rate:** ${data.kpis.acceptanceRate.current.toFixed(1)}% (${buildTrendLabel(data.kpis.acceptanceRate.trend)})`
  );
  lines.push(
    `**Reply Rate:** ${data.kpis.replyRate.current.toFixed(1)}% (${buildTrendLabel(data.kpis.replyRate.trend)})`
  );
  lines.push(
    `**Replies:** ${data.kpis.repliesReceived.current}`
  );
  lines.push("");

  // Notable Conversations
  lines.push("### Notable Conversations");
  if (data.notableConversations.length === 0) {
    lines.push("- Keine bemerkenswerten Conversations diese Woche");
  } else {
    data.notableConversations.forEach((c: AMNotableConversation) => {
      const company = c.leadCompany ? ` (${c.leadCompany})` : "";
      const tag = c.tagCategory ? ` — ${c.tagCategory}` : "";
      lines.push(`- ${c.leadName}${company}${tag}`);
    });
  }
  lines.push("");

  // Risks
  lines.push("### Risiken");
  if (data.risks.length === 0) {
    lines.push("- Keine aktuellen Risiken");
  } else {
    data.risks.forEach((r: EmergingRisk) => {
      lines.push(`- [${r.severity.toUpperCase()}] ${r.description}`);
    });
  }
  lines.push("");

  // Talking Points
  lines.push("### Talking Points");
  if (data.talkingPoints.autoGenerated) {
    data.talkingPoints.autoGenerated.split("\n").forEach((line: string) => {
      if (line.trim()) {
        lines.push(line.startsWith("-") || line.startsWith("*") ? line : `- ${line}`);
      }
    });
  }
  if (userNotes) {
    lines.push("");
    lines.push("**Eigene Notizen:**");
    userNotes.split("\n").forEach((line: string) => {
      if (line.trim()) {
        lines.push(line.startsWith("-") || line.startsWith("*") ? line : `- ${line}`);
      }
    });
  }

  return lines.join("\n");
}

export function AMCopyButton({ data, userNotes }: AMCopyButtonProps) {
  const [copyState, setCopyState] = useState<"idle" | "copied" | "error">("idle");

  const handleCopy = async () => {
    const markdown = buildMarkdown(data, userNotes);

    try {
      await navigator.clipboard.writeText(markdown);
      setCopyState("copied");
      toast.success("Summary in Zwischenablage kopiert");
      setTimeout(() => setCopyState("idle"), 2000);
    } catch {
      setCopyState("error");
      toast.error("Kopieren fehlgeschlagen. Bitte manuell kopieren.");
      setTimeout(() => setCopyState("idle"), 2000);
    }
  };

  return (
    <Button
      variant="outline"
      size="sm"
      onClick={handleCopy}
      className="gap-2"
      aria-label="Summary als Markdown kopieren"
    >
      {copyState === "idle" && (
        <>
          <Copy className="h-4 w-4" aria-hidden="true" />
          Summary kopieren
        </>
      )}
      {copyState === "copied" && (
        <>
          <Check className="h-4 w-4 text-emerald-600" aria-hidden="true" />
          Kopiert!
        </>
      )}
      {copyState === "error" && (
        <>
          <X className="h-4 w-4 text-red-600" aria-hidden="true" />
          Fehlgeschlagen
        </>
      )}
    </Button>
  );
}
