"use client";

import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Separator } from "@/components/ui/separator";
import { CheckCircle, Loader2, AlertCircle, Archive } from "lucide-react";
import { cn } from "@/lib/utils";
import type { TalkingPointsData, WeekArchiveEntry } from "@/lib/types/am-summary";

interface AMTalkingPointsProps {
  talkingPoints: TalkingPointsData | null;
  weekArchive: WeekArchiveEntry[];
  selectedWeek: string;
  saveStatus: "idle" | "saving" | "saved" | "error";
  onNotesChange: (notes: string) => void;
  onWeekChange: (weekStart: string) => void;
}

function SaveStatusIndicator({
  status,
}: {
  status: "idle" | "saving" | "saved" | "error";
}) {
  if (status === "idle") return null;

  return (
    <span
      className={cn("inline-flex items-center gap-1 text-xs", {
        "text-muted-foreground": status === "saving",
        "text-emerald-600": status === "saved",
        "text-red-600": status === "error",
      })}
      aria-live="polite"
    >
      {status === "saving" && (
        <>
          <Loader2 className="h-3 w-3 animate-spin" aria-hidden="true" />
          Speichert...
        </>
      )}
      {status === "saved" && (
        <>
          <CheckCircle className="h-3 w-3" aria-hidden="true" />
          Gespeichert
        </>
      )}
      {status === "error" && (
        <>
          <AlertCircle className="h-3 w-3" aria-hidden="true" />
          Fehler beim Speichern
        </>
      )}
    </span>
  );
}

function formatWeekLabel(entry: WeekArchiveEntry): string {
  if (entry.label) return entry.label;
  const date = new Date(entry.weekStart);
  const endDate = new Date(date);
  endDate.setDate(endDate.getDate() + 6);
  return `${date.toLocaleDateString("de-DE", {
    day: "2-digit",
    month: "2-digit",
  })} - ${endDate.toLocaleDateString("de-DE", {
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
  })}`;
}

export function AMTalkingPoints({
  talkingPoints,
  weekArchive,
  selectedWeek,
  saveStatus,
  onNotesChange,
  onWeekChange,
}: AMTalkingPointsProps) {
  const currentWeekEntry = weekArchive.find((w) => w.isCurrent);
  const isCurrentWeek = selectedWeek === currentWeekEntry?.weekStart;
  const isReadOnly = !isCurrentWeek;

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between flex-wrap gap-2">
        <h3 className="text-lg font-semibold">Talking Points</h3>
        <div className="flex items-center gap-3">
          <SaveStatusIndicator status={saveStatus} />
          {weekArchive.length > 0 && (
            <Select value={selectedWeek} onValueChange={onWeekChange}>
              <SelectTrigger className="w-[220px]" aria-label="Woche auswaehlen">
                <SelectValue placeholder="Woche waehlen" />
              </SelectTrigger>
              <SelectContent>
                {weekArchive.map((entry) => (
                  <SelectItem key={entry.weekStart} value={entry.weekStart}>
                    <span className="flex items-center gap-2">
                      {entry.isCurrent ? (
                        <span className="font-medium">Aktuelle Woche</span>
                      ) : (
                        <>
                          <Archive className="h-3 w-3 text-muted-foreground" aria-hidden="true" />
                          {formatWeekLabel(entry)}
                        </>
                      )}
                    </span>
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          )}
        </div>
      </div>

      <Card>
        <CardHeader className="pb-3">
          <CardTitle className="text-sm text-muted-foreground">
            Auto-generierte Punkte
          </CardTitle>
        </CardHeader>
        <CardContent className="pt-0">
          {talkingPoints?.autoGenerated ? (
            <div className="text-sm whitespace-pre-line leading-relaxed bg-muted/30 rounded-md p-3">
              {talkingPoints.autoGenerated}
            </div>
          ) : (
            <p className="text-sm text-muted-foreground italic">
              Keine auto-generierten Talking Points verfuegbar
            </p>
          )}

          <Separator className="my-4" />

          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <h4 className="text-sm font-medium">
                Eigene Notizen
                {isReadOnly && (
                  <span className="ml-2 text-xs text-muted-foreground font-normal">
                    (read-only)
                  </span>
                )}
              </h4>
            </div>
            <Textarea
              value={talkingPoints?.userNotes ?? ""}
              onChange={(e) => onNotesChange(e.target.value)}
              placeholder={
                isReadOnly
                  ? "Keine Notizen fuer diese Woche"
                  : "Eigene Notizen und Talking Points hier hinzufuegen..."
              }
              disabled={isReadOnly}
              className="min-h-[120px] resize-y"
              aria-label="Eigene Talking Points Notizen"
            />
            {isReadOnly && (
              <p className="text-xs text-muted-foreground">
                Vergangene Wochen koennen nicht bearbeitet werden.
              </p>
            )}
          </div>

          {weekArchive.length <= 1 && (
            <p className="text-xs text-muted-foreground mt-3 italic">
              Noch kein Archiv vorhanden
            </p>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
