// PROJ-7: Account Manager Campaign Summary Types

import type { HealthStatus, ActivityLevel, TrendDirection } from "@/lib/types/campaign";
import type { ReplyCategory, ConversationWithTag } from "@/lib/types/messaging";

/** Overall assessment of week-over-week performance */
export type WeekAssessment = "improved" | "stable" | "declining";

/** Risk severity levels */
export type RiskSeverity = "warning" | "critical";

/** A KPI metric with current, previous, and trend data */
export interface AMMetric {
  current: number;
  previous: number | null;
  trend: TrendDirection | null;
  changePercent: number | null;
}

/** Workspace card data for the overview page */
export interface AMWorkspaceCardData {
  workspace: string;
  healthStatus: HealthStatus;
  activityLevel: ActivityLevel;
  lastActiveDate: string | null;
  connectionsSent7d: AMMetric;
  replyRate7d: AMMetric;
  repliesReceived7d: AMMetric;
  notableConversationsCount: number;
  riskCount: number;
}

/** Overview response from GET /api/am-summary */
export interface AMSummaryResponse {
  workspaces: AMWorkspaceCardData[];
  userAssignments: string[];
  hasAssignments: boolean;
}

/** An individual emerging risk */
export interface EmergingRisk {
  id: string;
  description: string;
  severity: RiskSeverity;
  recommendedAction: string;
  metricType: string;
  values?: string[];
}

/** Talking points data for a given week */
export interface TalkingPointsData {
  autoGenerated: string;
  userNotes: string;
  weekStart: string;
  updatedAt: string | null;
}

/** Week archive entry */
export interface WeekArchiveEntry {
  weekStart: string;
  label: string;
  isCurrent: boolean;
}

/** KPI section data */
export interface AMKPIData {
  connectionsSent: AMMetric;
  acceptanceRate: AMMetric;
  messagesStarted: AMMetric;
  replyRate: AMMetric;
  repliesReceived: AMMetric;
  weekAssessment: WeekAssessment;
}

/** Notable conversation for display (simplified from full ConversationWithTag) */
export interface AMNotableConversation {
  conversationId: string;
  leadName: string;
  leadPosition: string | null;
  leadCompany: string | null;
  tagCategory: ReplyCategory | null;
  isNotable: boolean;
  lastMessagePreview: string | null;
  lastMessageAt: string | null;
  conversationDepthCategory: string | null;
  // Full conversation data for expanded view
  fullConversation: ConversationWithTag;
}

/** Detail response from GET /api/am-summary/[workspace] */
export interface AMWorkspaceDetailResponse {
  workspace: string;
  healthStatus: HealthStatus;
  activityLevel: ActivityLevel;
  lastActiveDate: string | null;
  dateRange: {
    start: string;
    end: string;
  };
  kpis: AMKPIData;
  notableConversations: AMNotableConversation[];
  risks: EmergingRisk[];
  talkingPoints: TalkingPointsData;
  weekArchive: WeekArchiveEntry[];
}

/** Request body for PUT /api/am-summary/talking-points */
export interface TalkingPointsUpdateRequest {
  workspace: string;
  weekStart: string;
  userNotes: string;
}

/** Response from PUT /api/am-summary/talking-points */
export interface TalkingPointsUpdateResponse {
  success: boolean;
  updatedAt: string;
}

/** Workspace assignment for admin settings */
export interface WorkspaceAssignment {
  userId: string;
  fullName: string | null;
  email: string | null;
  role: string;
  assignedWorkspaces: string[];
}

/** Response from GET /api/am-summary/assignments */
export interface AssignmentsResponse {
  assignments: WorkspaceAssignment[];
  availableWorkspaces: string[];
}

/** Request body for PUT /api/am-summary/assignments */
export interface AssignmentUpdateRequest {
  userId: string;
  workspaces: string[];
}
